# Generated by Django 3.2.4 on 2021-07-06 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210706_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('img_url', models.TextField(null=True)),
                ('date_posted', models.DateTimeField()),
                ('description', models.TextField()),
                ('tweet_url', models.TextField(null=True)),
                ('article_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', unique=True)),
            ],
        ),
    ]
