# Generated by Django 3.2.4 on 2021-07-07 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_article_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_detail',
            name='likes',
            field=models.ManyToManyField(related_name='articles_article_detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
